"""
Embedded MediaMTX on the controller (Option B): one server pulls all camera URLs.

Requires the ``mediamtx`` binary on PATH or ``CONTROLLER_MEDIAMTX_BIN``.
Disable with ``CONTROLLER_MEDIAMTX_DISABLED=1``.
"""

from __future__ import annotations

import json
import logging
import os
import shutil
import subprocess
import threading
import time
from pathlib import Path
from typing import Any, Optional

from . import camera_store

logger = logging.getLogger(__name__)

_BACKEND_ROOT = Path(__file__).resolve().parent.parent
CONFIG_PATH = _BACKEND_ROOT / "data" / "mediamtx.generated.yml"
_STDERR_LOG = _BACKEND_ROOT / "data" / "mediamtx.stderr.log"
_BUNDLED_MEDIAMTX = _BACKEND_ROOT / "bin" / "mediamtx"

_proc: Optional[subprocess.Popen] = None
_last_yaml: str = ""
_last_start_error: str = ""
_lock = threading.RLock()
_debounce_timer: Optional[threading.Timer] = None


def _webrtc_listen_address() -> str:
    v = os.environ.get("CONTROLLER_MEDIAMTX_WEBRTC_ADDRESS", "").strip()
    return v if v else ":8889"


def _hls_listen_address() -> str:
    v = os.environ.get("CONTROLLER_MEDIAMTX_HLS_ADDRESS", "").strip()
    return v if v else ":8888"


def _rtsp_listen_address() -> str:
    v = os.environ.get("CONTROLLER_MEDIAMTX_RTSP_ADDRESS", "").strip()
    return v if v else ":8554"


def _hls_enabled() -> bool:
    return os.environ.get("CONTROLLER_MEDIAMTX_HLS_DISABLED", "").strip().lower() not in (
        "1",
        "true",
        "yes",
        "on",
    )


def hls_enabled() -> bool:
    return _hls_enabled()


def camera_id_to_mediamtx_path(cameras: list[dict[str, Any]]) -> dict[int, str]:
    """
    Map camera id -> MediaMTX path key exactly as in generated YAML
    (see build_mediamtx_yaml).
    """
    path_sources: dict[str, str] = {}
    id_to_key: dict[int, str] = {}
    for cam in cameras:
        url = cam.get("url")
        if not isinstance(url, str) or not url.strip():
            continue
        key = _safe_path_key(cam)
        if key in path_sources:
            key = f"{key}_{int(cam['id'])}"
        path_sources[key] = url.strip()
        id_to_key[int(cam["id"])] = key
    return id_to_key


def mediamtx_binary() -> Optional[str]:
    env_bin = os.environ.get("CONTROLLER_MEDIAMTX_BIN", "").strip()
    candidates: list[str] = []
    if env_bin:
        candidates.append(env_bin)
    if _BUNDLED_MEDIAMTX.is_file():
        candidates.append(str(_BUNDLED_MEDIAMTX.resolve()))
    candidates.append("mediamtx")
    for c in candidates:
        if not c:
            continue
        p = Path(c)
        if p.is_file():
            return str(p.resolve())
        w = shutil.which(c)
        if w:
            return w
    return None


def should_run_mediamtx() -> bool:
    if os.environ.get("CONTROLLER_MEDIAMTX_DISABLED", "").strip().lower() in (
        "1",
        "true",
        "yes",
        "on",
    ):
        return False
    if os.environ.get("CONTROLLER_MEDIAMTX_ENABLED", "").strip().lower() in (
        "0",
        "false",
        "no",
        "off",
    ):
        return False
    return mediamtx_binary() is not None


def _safe_path_key(cam: dict[str, Any]) -> str:
    raw = camera_store.mediamtx_path_for_camera(cam).strip().strip("/")
    if not raw:
        raw = f"cam{int(cam['id'])}"
    safe = "".join(ch if ch.isalnum() or ch in "-_" else "_" for ch in raw)
    safe = safe.strip("_") or f"cam{int(cam['id'])}"
    return safe


def build_mediamtx_yaml(cameras: list[dict[str, Any]]) -> str:
    """Minimal MediaMTX config: WebRTC HTTP UI + RTSP pull sources per path."""
    path_sources: dict[str, str] = {}
    for cam in cameras:
        url = cam.get("url")
        if not isinstance(url, str) or not url.strip():
            continue
        key = _safe_path_key(cam)
        if key in path_sources:
            key = f"{key}_{int(cam['id'])}"
        path_sources[key] = url.strip()

    lines = [
        "# Generated by SmartCam controller — overwritten on camera changes.",
        "logLevel: info",
        "logDestinations: [stdout]",
        "api: false",
        "rtsp: yes",
        f"rtspAddress: {_rtsp_listen_address()}",
        "webrtc: true",
        f"webrtcAddress: {_webrtc_listen_address()}",
        # webrtcAllowOrigin(s) is intentionally omitted: the field name changed
        # between MediaMTX versions (singular `webrtcAllowOrigin` in <=1.9.x,
        # plural `webrtcAllowOrigins` list in newer releases) and MediaMTX
        # rejects unknown YAML keys strictly. We embed the live view as an
        # <iframe src="http://<controller>:8889/<path>/">, so the WHEP handshake
        # is same-origin to the reader page MediaMTX serves and no extra CORS
        # allow-list is required.
    ]
    if _hls_enabled():
        lines.extend(
            [
                "hls: true",
                f"hlsAddress: {_hls_listen_address()}",
                "hlsAllowOrigins: ['*']",
                # mpegts + always-on remux: best compatibility with hls.js and first viewer.
                "hlsVariant: mpegts",
                "hlsAlwaysRemux: true",
            ]
        )
    if not path_sources:
        lines.append("paths: {}")
    else:
        lines.append("paths:")
        for key in sorted(path_sources.keys()):
            src = json.dumps(path_sources[key])
            lines.append(f"  {key}:")
            lines.append(f"    source: {src}")
            lines.append("    sourceOnDemand: false")
            # TCP is more reliable than UDP for Pi-to-Pi RTSP over Wi‑Fi/Ethernet.
            lines.append("    rtspTransport: tcp")
    return "\n".join(lines) + "\n"


def _stop_proc() -> None:
    global _proc
    if _proc is None:
        return
    p = _proc
    _proc = None
    try:
        p.terminate()
        p.wait(timeout=8)
    except subprocess.TimeoutExpired:
        try:
            p.kill()
            p.wait(timeout=3)
        except Exception:
            pass
    except Exception as e:
        logger.warning("mediamtx terminate: %s", e)


def _apply_config(yaml_text: str) -> None:
    global _proc, _last_yaml, _last_start_error
    bin_path = mediamtx_binary()
    if not bin_path:
        return

    if (
        yaml_text == _last_yaml
        and _proc is not None
        and _proc.poll() is None
    ):
        return

    CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
    CONFIG_PATH.write_text(yaml_text, encoding="utf-8")
    _last_yaml = yaml_text

    _stop_proc()
    try:
        _STDERR_LOG.parent.mkdir(parents=True, exist_ok=True)
        err_f = open(_STDERR_LOG, "w", encoding="utf-8")
        _proc = subprocess.Popen(
            [bin_path, str(CONFIG_PATH)],
            stdin=subprocess.DEVNULL,
            stdout=subprocess.DEVNULL,
            stderr=err_f,
            cwd=str(CONFIG_PATH.parent),
        )
        err_f.close()
        time.sleep(0.5)
        if _proc.poll() is not None:
            tail = _read_stderr_tail()
            _last_start_error = (
                f"mediamtx exited immediately (code {_proc.returncode}). {tail}".strip()
            )
            logger.error(_last_start_error)
            _proc = None
            return
        npaths = yaml_text.count("\n    source:")
        _last_start_error = ""
        logger.info(
            "mediamtx started pid=%s config=%s paths=%s",
            _proc.pid,
            CONFIG_PATH.name,
            npaths,
        )
    except OSError as e:
        _last_start_error = str(e)
        logger.error("mediamtx failed to start: %s", e)


def _read_stderr_tail(max_bytes: int = 4000) -> str:
    try:
        if not _STDERR_LOG.is_file():
            return ""
        data = _STDERR_LOG.read_text(encoding="utf-8", errors="replace")
        return data[-max_bytes:].strip()
    except OSError:
        return ""


def _restart_job() -> None:
    global _debounce_timer
    with _lock:
        _debounce_timer = None
    try:
        yaml_text = build_mediamtx_yaml(camera_store.list_cameras())
        _apply_config(yaml_text)
    except Exception:
        logger.exception("mediamtx config/regenerate failed")


def _schedule_restart() -> None:
    global _debounce_timer
    with _lock:
        if _debounce_timer is not None:
            _debounce_timer.cancel()
        _debounce_timer = threading.Timer(1.2, _restart_job)
        _debounce_timer.daemon = True
        _debounce_timer.start()


def _on_camera_store_changed() -> None:
    if not should_run_mediamtx():
        return
    _schedule_restart()


def start_embedded() -> None:
    """Call from FastAPI lifespan after loading persisted cameras."""
    if not should_run_mediamtx():
        if os.environ.get("CONTROLLER_MEDIAMTX_DISABLED", "").strip().lower() not in (
            "1",
            "true",
            "yes",
            "on",
        ):
            logger.info(
                "MediaMTX not started: no mediamtx binary on PATH "
                "(install from https://github.com/bluenviron/mediamtx/releases "
                "or set CONTROLLER_MEDIAMTX_BIN). "
                "Set CONTROLLER_MEDIAMTX_DISABLED=1 to hide this log."
            )
        return
    camera_store.add_change_listener(_on_camera_store_changed)
    try:
        yaml_text = build_mediamtx_yaml(camera_store.list_cameras())
        _apply_config(yaml_text)
    except Exception:
        logger.exception("mediamtx initial start failed")


def path_map_for_cameras() -> dict[int, str]:
    return camera_id_to_mediamtx_path(camera_store.list_cameras())


def hls_local_origin() -> str:
    """Loopback base for controller MediaMTX HLS (no path suffix)."""
    addr = _hls_listen_address().strip()
    if not addr.startswith(":"):
        return f"http://{addr}"
    port = addr.rsplit(":", 1)[-1]
    return f"http://127.0.0.1:{port}"


def hls_playlist_url(path_key: str, host: str = "127.0.0.1") -> str:
    p = (path_key or "camera1").strip().strip("/")
    if host in ("127.0.0.1", "localhost"):
        base = hls_local_origin()
    else:
        hls_port = _hls_listen_address().rsplit(":", 1)[-1]
        base = f"http://{host}:{hls_port}"
    return f"{base}/{p}/index.m3u8"


def probe_rtsp(url: str, timeout_sec: float = 8.0) -> dict[str, Any]:
    """Quick ffprobe check from the controller (edge must accept TCP RTSP)."""
    out: dict[str, Any] = {"url": url, "probe_available": False, "reachable": None}
    if not isinstance(url, str) or not url.strip().startswith("rtsp://"):
        out["error"] = "not an rtsp url"
        return out
    ffprobe = shutil.which("ffprobe")
    if not ffprobe:
        out["hint"] = "install ffmpeg (ffprobe) on the controller for RTSP checks"
        return out
    out["probe_available"] = True
    cmd = [
        ffprobe,
        "-hide_banner",
        "-loglevel",
        "error",
        "-rtsp_transport",
        "tcp",
        "-i",
        url.strip(),
        "-show_entries",
        "stream=codec_type",
        "-of",
        "csv=p=0",
    ]
    try:
        r = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=max(3.0, timeout_sec) + 2.0,
        )
        out["returncode"] = int(r.returncode)
        if r.returncode == 0 and "video" in (r.stdout or ""):
            out["reachable"] = True
        else:
            out["reachable"] = False
            err = (r.stderr or r.stdout or "").strip()
            if err:
                out["stderr"] = err[-800:]
    except subprocess.TimeoutExpired:
        out["reachable"] = False
        out["error"] = "timeout"
    except OSError as e:
        out["reachable"] = False
        out["error"] = str(e)
    return out


def status_dict() -> dict[str, Any]:
    """For GET /system/mediamtx — why the browser may see 'connection refused' on :8889."""
    with _lock:
        running = _proc is not None and _proc.poll() is None
        pid = int(_proc.pid) if running and _proc is not None else None
    w = _webrtc_listen_address()
    port = w.rsplit(":", 1)[-1] if ":" in w else "8889"
    hls_a = _hls_listen_address()
    hls_port = hls_a.rsplit(":", 1)[-1] if ":" in hls_a else "8888"
    rtsp_a = _rtsp_listen_address()
    paths = path_map_for_cameras()
    return {
        "should_run": should_run_mediamtx(),
        "binary_path": mediamtx_binary(),
        "process_running": running,
        "pid": pid,
        "config_path": str(CONFIG_PATH.resolve()),
        "stderr_log": str(_STDERR_LOG.resolve()),
        "stderr_tail": _read_stderr_tail() or None,
        "paths": paths,
        "webrtc_listen_address": w,
        "player_port": port,
        "hls_enabled": _hls_enabled(),
        "hls_listen_address": hls_a,
        "hls_player_port": hls_port,
        "rtsp_listen_address": rtsp_a,
        "last_start_error": _last_start_error or None,
        "ui_hint": (
            f"HLS: http://<controller-lan-ip>:{hls_port}/<path>/index.m3u8 — "
            "edge must publish RTSP first (ffprobe rtsp://<edge>:8554/<path>)."
        ),
    }


def probe_hls_local(path_key: str) -> dict[str, Any]:
    """HEAD the local HLS playlist (controller loopback)."""
    import urllib.error
    import urllib.request

    url = hls_playlist_url(path_key, "127.0.0.1")
    out: dict[str, Any] = {"url": url, "reachable": False, "status": None}
    for method in ("HEAD", "GET"):
        try:
            req = urllib.request.Request(url, method=method)
            with urllib.request.urlopen(req, timeout=4.0) as resp:
                out["status"] = int(resp.status)
                out["reachable"] = 200 <= int(resp.status) < 400
                out["method"] = method
                break
        except urllib.error.HTTPError as e:
            out["status"] = int(e.code)
            out["reachable"] = False
            out["method"] = method
        except Exception as e:
            out["error"] = str(e)
            out["method"] = method
    return out


def restart_embedded() -> dict[str, Any]:
    """Force-regenerate YAML and restart MediaMTX (e.g. after installing the binary)."""
    global _last_yaml
    if not should_run_mediamtx():
        return status_dict()
    with _lock:
        _last_yaml = ""
    try:
        yaml_text = build_mediamtx_yaml(camera_store.list_cameras())
        _apply_config(yaml_text)
    except Exception:
        logger.exception("mediamtx manual restart failed")
    return status_dict()


def stop_embedded() -> None:
    global _debounce_timer
    camera_store.remove_change_listener(_on_camera_store_changed)
    with _lock:
        if _debounce_timer is not None:
            _debounce_timer.cancel()
            _debounce_timer = None
        time.sleep(0.05)
    _stop_proc()
