"""
Embedded MediaMTX on the controller (Option B): one server pulls all camera URLs.

Requires the ``mediamtx`` binary on PATH or ``CONTROLLER_MEDIAMTX_BIN``.
Disable with ``CONTROLLER_MEDIAMTX_DISABLED=1``.
"""

from __future__ import annotations

import json
import logging
import os
import shutil
import subprocess
import threading
import time
from pathlib import Path
from typing import Any, Optional

from . import camera_store

logger = logging.getLogger(__name__)

_BACKEND_ROOT = Path(__file__).resolve().parent.parent
CONFIG_PATH = _BACKEND_ROOT / "data" / "mediamtx.generated.yml"
_BUNDLED_MEDIAMTX = _BACKEND_ROOT / "bin" / "mediamtx"

_proc: Optional[subprocess.Popen] = None
_last_yaml: str = ""
_last_start_error: str = ""
_lock = threading.RLock()
_debounce_timer: Optional[threading.Timer] = None


def _webrtc_listen_address() -> str:
    v = os.environ.get("CONTROLLER_MEDIAMTX_WEBRTC_ADDRESS", "").strip()
    return v if v else ":8889"


def _hls_listen_address() -> str:
    v = os.environ.get("CONTROLLER_MEDIAMTX_HLS_ADDRESS", "").strip()
    return v if v else ":8888"


def _hls_enabled() -> bool:
    return os.environ.get("CONTROLLER_MEDIAMTX_HLS_DISABLED", "").strip().lower() not in (
        "1",
        "true",
        "yes",
        "on",
    )


def camera_id_to_mediamtx_path(cameras: list[dict[str, Any]]) -> dict[int, str]:
    """
    Map camera id -> MediaMTX path key exactly as in generated YAML
    (see build_mediamtx_yaml).
    """
    path_sources: dict[str, str] = {}
    id_to_key: dict[int, str] = {}
    for cam in cameras:
        url = cam.get("url")
        if not isinstance(url, str) or not url.strip():
            continue
        key = _safe_path_key(cam)
        if key in path_sources:
            key = f"{key}_{int(cam['id'])}"
        path_sources[key] = url.strip()
        id_to_key[int(cam["id"])] = key
    return id_to_key


def mediamtx_binary() -> Optional[str]:
    env_bin = os.environ.get("CONTROLLER_MEDIAMTX_BIN", "").strip()
    candidates: list[str] = []
    if env_bin:
        candidates.append(env_bin)
    if _BUNDLED_MEDIAMTX.is_file():
        candidates.append(str(_BUNDLED_MEDIAMTX.resolve()))
    candidates.append("mediamtx")
    for c in candidates:
        if not c:
            continue
        p = Path(c)
        if p.is_file():
            return str(p.resolve())
        w = shutil.which(c)
        if w:
            return w
    return None


def should_run_mediamtx() -> bool:
    if os.environ.get("CONTROLLER_MEDIAMTX_DISABLED", "").strip().lower() in (
        "1",
        "true",
        "yes",
        "on",
    ):
        return False
    if os.environ.get("CONTROLLER_MEDIAMTX_ENABLED", "").strip().lower() in (
        "0",
        "false",
        "no",
        "off",
    ):
        return False
    return mediamtx_binary() is not None


def _safe_path_key(cam: dict[str, Any]) -> str:
    raw = camera_store.mediamtx_path_for_camera(cam).strip().strip("/")
    if not raw:
        raw = f"cam{int(cam['id'])}"
    safe = "".join(ch if ch.isalnum() or ch in "-_" else "_" for ch in raw)
    safe = safe.strip("_") or f"cam{int(cam['id'])}"
    return safe


def build_mediamtx_yaml(cameras: list[dict[str, Any]]) -> str:
    """Minimal MediaMTX config: WebRTC HTTP UI + RTSP pull sources per path."""
    path_sources: dict[str, str] = {}
    for cam in cameras:
        url = cam.get("url")
        if not isinstance(url, str) or not url.strip():
            continue
        key = _safe_path_key(cam)
        if key in path_sources:
            key = f"{key}_{int(cam['id'])}"
        path_sources[key] = url.strip()

    lines = [
        "# Generated by SmartCam controller — overwritten on camera changes.",
        "logLevel: warn",
        "logDestinations: [stdout]",
        "api: false",
        "webrtc: true",
        f"webrtcAddress: {_webrtc_listen_address()}",
        # webrtcAllowOrigin(s) is intentionally omitted: the field name changed
        # between MediaMTX versions (singular `webrtcAllowOrigin` in <=1.9.x,
        # plural `webrtcAllowOrigins` list in newer releases) and MediaMTX
        # rejects unknown YAML keys strictly. We embed the live view as an
        # <iframe src="http://<controller>:8889/<path>/">, so the WHEP handshake
        # is same-origin to the reader page MediaMTX serves and no extra CORS
        # allow-list is required.
    ]
    if _hls_enabled():
        lines.extend(
            [
                "hls: true",
                f"hlsAddress: {_hls_listen_address()}",
                "hlsAllowOrigins: ['*']",
            ]
        )
    if not path_sources:
        lines.append("paths: {}")
    else:
        lines.append("paths:")
        for key in sorted(path_sources.keys()):
            src = json.dumps(path_sources[key])
            lines.append(f"  {key}:")
            lines.append(f"    source: {src}")
            # TCP is more reliable than UDP for Pi-to-Pi RTSP over Wi‑Fi/Ethernet.
            lines.append("    rtspTransport: tcp")
    return "\n".join(lines) + "\n"


def _stop_proc() -> None:
    global _proc
    if _proc is None:
        return
    p = _proc
    _proc = None
    try:
        p.terminate()
        p.wait(timeout=8)
    except subprocess.TimeoutExpired:
        try:
            p.kill()
            p.wait(timeout=3)
        except Exception:
            pass
    except Exception as e:
        logger.warning("mediamtx terminate: %s", e)


def _apply_config(yaml_text: str) -> None:
    global _proc, _last_yaml, _last_start_error
    bin_path = mediamtx_binary()
    if not bin_path:
        return

    if (
        yaml_text == _last_yaml
        and _proc is not None
        and _proc.poll() is None
    ):
        return

    CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
    CONFIG_PATH.write_text(yaml_text, encoding="utf-8")
    _last_yaml = yaml_text

    _stop_proc()
    try:
        _proc = subprocess.Popen(
            [bin_path, str(CONFIG_PATH)],
            stdin=subprocess.DEVNULL,
            cwd=str(CONFIG_PATH.parent),
        )
        npaths = yaml_text.count("\n    source:")
        _last_start_error = ""
        logger.info(
            "mediamtx started pid=%s config=%s paths=%s",
            _proc.pid,
            CONFIG_PATH.name,
            npaths,
        )
    except OSError as e:
        _last_start_error = str(e)
        logger.error("mediamtx failed to start: %s", e)


def _restart_job() -> None:
    global _debounce_timer
    with _lock:
        _debounce_timer = None
    try:
        yaml_text = build_mediamtx_yaml(camera_store.list_cameras())
        _apply_config(yaml_text)
    except Exception:
        logger.exception("mediamtx config/regenerate failed")


def _schedule_restart() -> None:
    global _debounce_timer
    with _lock:
        if _debounce_timer is not None:
            _debounce_timer.cancel()
        _debounce_timer = threading.Timer(1.2, _restart_job)
        _debounce_timer.daemon = True
        _debounce_timer.start()


def _on_camera_store_changed() -> None:
    if not should_run_mediamtx():
        return
    _schedule_restart()


def start_embedded() -> None:
    """Call from FastAPI lifespan after loading persisted cameras."""
    if not should_run_mediamtx():
        if os.environ.get("CONTROLLER_MEDIAMTX_DISABLED", "").strip().lower() not in (
            "1",
            "true",
            "yes",
            "on",
        ):
            logger.info(
                "MediaMTX not started: no mediamtx binary on PATH "
                "(install from https://github.com/bluenviron/mediamtx/releases "
                "or set CONTROLLER_MEDIAMTX_BIN). "
                "Set CONTROLLER_MEDIAMTX_DISABLED=1 to hide this log."
            )
        return
    camera_store.add_change_listener(_on_camera_store_changed)
    try:
        yaml_text = build_mediamtx_yaml(camera_store.list_cameras())
        _apply_config(yaml_text)
    except Exception:
        logger.exception("mediamtx initial start failed")


def status_dict() -> dict[str, Any]:
    """For GET /system/mediamtx — why the browser may see 'connection refused' on :8889."""
    with _lock:
        running = _proc is not None and _proc.poll() is None
        pid = int(_proc.pid) if running and _proc is not None else None
    w = _webrtc_listen_address()
    port = w.rsplit(":", 1)[-1] if ":" in w else "8889"
    hls_a = _hls_listen_address()
    hls_port = hls_a.rsplit(":", 1)[-1] if ":" in hls_a else "8888"
    return {
        "should_run": should_run_mediamtx(),
        "binary_path": mediamtx_binary(),
        "process_running": running,
        "pid": pid,
        "config_path": str(CONFIG_PATH.resolve()),
        "webrtc_listen_address": w,
        "player_port": port,
        "hls_enabled": _hls_enabled(),
        "hls_listen_address": hls_a,
        "hls_player_port": hls_port,
        "last_start_error": _last_start_error or None,
        "ui_hint": (
            f"Set VITE_MEDIAMTX_BASE to http://<this-host>:{port} "
            "(same machine as the API) if the live tile refuses to connect."
        ),
    }


def stop_embedded() -> None:
    global _debounce_timer
    camera_store.remove_change_listener(_on_camera_store_changed)
    with _lock:
        if _debounce_timer is not None:
            _debounce_timer.cancel()
            _debounce_timer = None
        time.sleep(0.05)
    _stop_proc()
