"""
Ensure an MQTT broker is reachable on the controller LAN address when the API starts.

By default, if ``CONTROLLER_MQTT_HOST`` is set, the backend starts a managed
``mosquitto`` process with a generated config under ``backend/data/`` that
listens on that host:port (edges cannot use a broker bound only to 127.0.0.1).

Disable with ``CONTROLLER_MOSQUITTO_DISABLED=1``.
Use ``CONTROLLER_MOSQUITTO_USE_SYSTEM=1`` to run ``systemctl start mosquitto``
instead (expects ``/etc/mosquitto/conf.d/smartcam.conf`` from install-mosquitto.sh).
"""

from __future__ import annotations

import logging
import os
import shutil
import socket
import subprocess
import time
from pathlib import Path
from typing import Any, Optional

logger = logging.getLogger(__name__)

_BACKEND_ROOT = Path(__file__).resolve().parent.parent
CONFIG_PATH = _BACKEND_ROOT / "data" / "mosquitto.smartcam.conf"
_PASSWD_PATH = _BACKEND_ROOT / "data" / "mosquitto.passwd"

_proc: Optional[subprocess.Popen] = None
_managed_by_backend = False
_last_start_error = ""


def _env_bool(name: str, default: bool = False) -> bool:
    v = os.environ.get(name, "").strip().lower()
    if not v:
        return default
    return v in ("1", "true", "yes", "on")


def mqtt_host() -> str:
    return os.environ.get("CONTROLLER_MQTT_HOST", "").strip()


def mqtt_port() -> int:
    try:
        return int(os.environ.get("CONTROLLER_MQTT_PORT", "1883"))
    except ValueError:
        return 1883


def should_manage_mosquitto() -> bool:
    if _env_bool("CONTROLLER_MOSQUITTO_DISABLED"):
        return False
    return bool(mqtt_host())


def mosquitto_binary() -> Optional[str]:
    env_bin = os.environ.get("CONTROLLER_MOSQUITTO_BIN", "").strip()
    for c in (env_bin, "mosquitto"):
        if not c:
            continue
        p = Path(c)
        if p.is_file():
            return str(p.resolve())
        w = shutil.which(c)
        if w:
            return w
    return None


def _is_reachable(host: str, port: int, timeout: float = 1.0) -> bool:
    if not host:
        return False
    try:
        with socket.create_connection((host, port), timeout=timeout):
            return True
    except OSError:
        return False


def _write_passwd_file(user: str, password: str) -> bool:
    _PASSWD_PATH.parent.mkdir(parents=True, exist_ok=True)
    passwd_bin = shutil.which("mosquitto_passwd")
    if not passwd_bin:
        logger.error(
            "mosquitto_passwd not found; install mosquitto-clients or use anonymous MQTT"
        )
        return False
    try:
        subprocess.run(
            [passwd_bin, "-c", "-b", str(_PASSWD_PATH), user, password],
            check=True,
            capture_output=True,
            text=True,
        )
        return True
    except subprocess.CalledProcessError as e:
        logger.error("mosquitto_passwd failed: %s", (e.stderr or e).strip())
        return False


def build_mosquitto_conf() -> str:
    host = mqtt_host()
    port = mqtt_port()
    user = (os.environ.get("CONTROLLER_MQTT_USER") or "").strip()
    pwd = os.environ.get("CONTROLLER_MQTT_PASSWORD") or ""

    lines = [
        "# Generated by smartcam controller backend (mosquitto_manager.py)",
        f"listener {port} {host}",
        "persistence true",
        f"persistence_location {_BACKEND_ROOT / 'data' / 'mosquitto_persistence'}",
    ]

    if user and pwd:
        if not _PASSWD_PATH.is_file():
            if not _write_passwd_file(user, pwd):
                raise RuntimeError("failed to create MQTT password file")
        lines.extend(
            [
                "allow_anonymous false",
                f"password_file {_PASSWD_PATH.resolve()}",
            ]
        )
    else:
        lines.append("allow_anonymous true")

    return "\n".join(lines) + "\n"


def _try_systemctl_start() -> bool:
    if not shutil.which("systemctl"):
        return False
    conf = Path("/etc/mosquitto/conf.d/smartcam.conf")
    if not conf.is_file():
        return False
    try:
        subprocess.run(
            ["systemctl", "start", "mosquitto"],
            check=True,
            capture_output=True,
            text=True,
            timeout=30,
        )
        return True
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired, OSError) as e:
        logger.warning("systemctl start mosquitto failed: %s", e)
        return False


def _stop_managed_proc() -> None:
    global _proc, _managed_by_backend
    if _proc is None:
        return
    try:
        if _proc.poll() is None:
            _proc.terminate()
            try:
                _proc.wait(timeout=5)
            except subprocess.TimeoutExpired:
                _proc.kill()
                _proc.wait(timeout=3)
    except OSError:
        pass
    _proc = None
    _managed_by_backend = False


def _start_embedded() -> None:
    global _proc, _managed_by_backend, _last_start_error

    bin_path = mosquitto_binary()
    if not bin_path:
        _last_start_error = "mosquitto binary not found (apt install mosquitto)"
        logger.error(_last_start_error)
        return

    try:
        conf_text = build_mosquitto_conf()
    except Exception as e:
        _last_start_error = str(e)
        logger.error("mosquitto config build failed: %s", e)
        return

    CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
    CONFIG_PATH.write_text(conf_text, encoding="utf-8")

    _stop_managed_proc()
    try:
        _proc = subprocess.Popen(
            [bin_path, "-c", str(CONFIG_PATH)],
            stdin=subprocess.DEVNULL,
        )
        _managed_by_backend = True
        _last_start_error = ""
        logger.info(
            "mosquitto started pid=%s listen=%s:%s config=%s",
            _proc.pid,
            mqtt_host(),
            mqtt_port(),
            CONFIG_PATH.name,
        )
    except OSError as e:
        _last_start_error = str(e)
        logger.error("mosquitto failed to start: %s", e)


def ensure_broker_started() -> None:
    """Call from FastAPI lifespan before mqtt_bridge.init_bridge_from_env."""
    global _last_start_error

    if not should_manage_mosquitto():
        return

    host = mqtt_host()
    port = mqtt_port()

    if _is_reachable(host, port):
        logger.info("MQTT broker already reachable at %s:%s", host, port)
        return

    if _env_bool("CONTROLLER_MOSQUITTO_USE_SYSTEM"):
        if _try_systemctl_start():
            time.sleep(0.4)
            if _is_reachable(host, port):
                logger.info("MQTT broker up via systemctl at %s:%s", host, port)
                return

    _start_embedded()
    for _ in range(10):
        if _proc is not None and _proc.poll() is not None:
            _last_start_error = _last_start_error or f"mosquitto exited code {_proc.returncode}"
            break
        if _is_reachable(host, port):
            return
        time.sleep(0.2)

    if not _is_reachable(host, port):
        logger.error(
            "MQTT broker not reachable at %s:%s after start (%s)",
            host,
            port,
            _last_start_error or "unknown",
        )


def status_dict() -> dict[str, Any]:
    host = mqtt_host()
    port = mqtt_port()
    reachable = _is_reachable(host, port) if host else False
    running = _proc is not None and _proc.poll() is None
    return {
        "should_manage": should_manage_mosquitto(),
        "binary_path": mosquitto_binary(),
        "managed_by_backend": _managed_by_backend,
        "process_running": running,
        "pid": int(_proc.pid) if running and _proc is not None else None,
        "listen_host": host or None,
        "listen_port": port,
        "broker_reachable": reachable,
        "config_path": str(CONFIG_PATH.resolve()) if CONFIG_PATH.is_file() else None,
        "last_start_error": _last_start_error or None,
        "ui_hint": (
            f"Edge agents need SURVEILLANCE_MQTT_HOST={host or '<controller-ip>'} "
            f"and port {port}. "
            "If only 127.0.0.1:1883 is listening, set CONTROLLER_MQTT_HOST in backend .env "
            "and restart uvicorn (broker starts with the API)."
        ),
    }


def stop_managed_broker() -> None:
    """Stop only the subprocess this backend started; leave system mosquitto running."""
    _stop_managed_proc()
