#!/usr/bin/env python3
"""
Write data/mediamtx.generated.yml from camera_store (same registry as the API).
Invoked by ../start.sh before starting the mediamtx binary.
"""

from __future__ import annotations

import json
import os
import sys
from urllib.parse import urlparse


def _backend_root() -> str:
    return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def main() -> int:
    backend = _backend_root()
    os.chdir(backend)
    if backend not in sys.path:
        sys.path.insert(0, backend)

    from app import camera_store
    from app.mediamtx_paths import mediamtx_path_key, rtsp_url, rtsp_url_has_userinfo

    cams = camera_store.list_cameras()
    usable: list[dict] = []
    for c in cams:
        if not isinstance(c, dict):
            continue
        u = rtsp_url(c)
        if not u or not (u.startswith("rtsp://") or u.startswith("rtsps://")):
            continue
        usable.append(c)

    data_dir = os.path.join(backend, "data")
    os.makedirs(data_dir, exist_ok=True)
    out_path = os.path.join(data_dir, "mediamtx.generated.yml")

    if not usable:
        if os.path.isfile(out_path):
            try:
                os.remove(out_path)
            except OSError as e:
                print(f"[mediamtx-yaml] could not remove {out_path}: {e}", flush=True)
        print("[mediamtx-yaml] no cameras with rtsp:// URL — skip MediaMTX config", flush=True)
        return 0

    lines = [
        "# Generated by scripts/generate_controller_mediamtx_yaml.py — do not hand-edit.",
        "logLevel: warn",
        "logDestinations: [stdout]",
        "readTimeout: 20s",
        "writeTimeout: 10s",
        "",
        "authMethod: internal",
        "authInternalUsers:",
        "- user: any",
        "  pass:",
        "  ips: []",
        "  permissions:",
        "  - action: publish",
        "    path:",
        "  - action: read",
        "    path:",
        "  - action: playback",
        "    path:",
        "",
        "api: yes",
        "apiAddress: 127.0.0.1:9997",
        "",
        "rtmp: no",
        "srt: no",
        "",
        "rtsp: yes",
        "rtspAddress: :8554",
        "",
        "hls: yes",
        "hlsAddress: :8888",
        "hlsAllowOrigin: '*'",
        "",
        "webrtc: yes",
        "webrtcAddress: :8889",
        "webrtcEncryption: no",
        "webrtcAllowOrigin: '*'",
        "",
        "paths:",
    ]
    for cam in usable:
        pk = mediamtx_path_key(cam)
        src = rtsp_url(cam)
        if src.startswith(("rtsp://", "rtsps://")) and not rtsp_url_has_userinfo(src):
            try:
                hint_host = urlparse(src).hostname or "camera-ip"
            except Exception:
                hint_host = "camera-ip"
            print(
                f"[mediamtx-yaml] WARN path {pk}: RTSP URL has no username — "
                f"VIGI/IP cameras often return 401; use rtsp://USER:PASS@{hint_host}:554/…",
                flush=True,
            )
        lines.append(f"  {pk}:")
        lines.append(f"    source: {json.dumps(src)}")
        lines.append("")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines).rstrip() + "\n")

    print(f"[mediamtx-yaml] wrote {out_path} ({len(usable)} path(s))", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
