#!/usr/bin/env bash
# Idempotent Mosquitto install for the Pi 5 controller. Binds MQTT to the LAN IP.
# Usage:
#   sudo ./install-mosquitto.sh [--anon] [--force] <lan-ipv4> [mqtt_user mqtt_password]
# Without --anon, mqtt_user and mqtt_password are required (password file at /etc/mosquitto/smartcam.passwd).

set -euo pipefail

ANON=0
FORCE=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --anon)
      ANON=1
      shift
      ;;
    --force)
      FORCE=1
      shift
      ;;
    -*)
      echo "Unknown option: $1" >&2
      exit 1
      ;;
    *)
      break
      ;;
  esac
done

LAN_IP="${1:-}"
MQTT_USER="${2:-}"
MQTT_PASS="${3:-}"

if [[ -z "$LAN_IP" ]]; then
  echo "Usage: sudo $0 [--anon] [--force] <lan-ipv4> [mqtt_user mqtt_password]" >&2
  exit 1
fi

if [[ "$EUID" -ne 0 ]]; then
  echo "Run as root (sudo)." >&2
  exit 1
fi

if [[ "$ANON" -eq 0 ]] && { [[ -z "$MQTT_USER" ]] || [[ -z "$MQTT_PASS" ]]; }; then
  echo "Without --anon, provide mqtt_user and mqtt_password after the LAN IP." >&2
  exit 1
fi

CONF="/etc/mosquitto/conf.d/smartcam.conf"
if [[ -f "$CONF" && "$FORCE" -eq 0 ]]; then
  echo "Refusing to overwrite $CONF (use --force)." >&2
  exit 1
fi

export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y mosquitto mosquitto-clients

if [[ "$ANON" -eq 1 ]]; then
  cat >"$CONF" <<EOF
# SmartCam — generated by install-mosquitto.sh
listener 1883 ${LAN_IP}
allow_anonymous true
EOF
else
  PWFILE="/etc/mosquitto/smartcam.passwd"
  if [[ "$FORCE" -eq 1 ]] || [[ ! -f "$PWFILE" ]]; then
    mosquitto_passwd -c -b "$PWFILE" "$MQTT_USER" "$MQTT_PASS"
    chmod 0640 "$PWFILE"
    chown root:mosquitto "$PWFILE" 2>/dev/null || true
  else
    mosquitto_passwd -b "$PWFILE" "$MQTT_USER" "$MQTT_PASS"
  fi
  cat >"$CONF" <<EOF
# SmartCam — generated by install-mosquitto.sh
listener 1883 ${LAN_IP}
allow_anonymous false
password_file ${PWFILE}
EOF
fi

chmod 0644 "$CONF"

systemctl enable mosquitto
systemctl restart mosquitto
echo "Mosquitto configured: listener 1883 ${LAN_IP} (see ${CONF})."
